# image par défaut du pipeline
image: gitlab.myusine.fr:5050/root/myusine/ubuntu:focal

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - builds
  - tests

build:
  stage: builds
  script:
    - echo "Build 1"
    - mkdir venv
    - echo "venv" > venv/package
  # génération d'un cache de dépendances logicielles
  cache:
    key: venv
    paths:
      - venv/
    policy: push

test:
  stage: tests
  script:
    - echo "Test 1"
    - cat venv/package
  # utilisation simple du cache venv
  cache:
    key: venv
    untracked: true
    policy: pull



