# image par défaut du pipeline
image: gitlab.myusine.fr:5050/root/myusine/docker:19

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - builds

build:
  stage: builds
  script:
    - docker build -t my_tomcat:1.0 .




