# image par défaut du pipeline
image: $CI_REGISTRY/root/myusine/docker:19

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - builds
  - tests

# services réseaux ajoutés à un job (ou au pipeline)
# les conteneurs sont disponible pour des connections
# depuis le conteneur du job
services:
  # - docker:19-dind
  - name: $CI_REGISTRY/root/myusine/docker:19-dind
    # hostname du service réseau
    alias: docker

build:
  stage: builds
  script:
    - docker build -t $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 .
    - >
      docker login 
      -u root 
      -p roottoor gitlab.myusine.fr:5050
    - docker push $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 .


test:
  stage: tests
  # test de l'image généré précédemment avec 
  # vérification du message de sortie
  # (attention au CMD qui ne renvoie pas le prompt)
  script:
    - >
      docker container run 
      --name test
      $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 
      /opt/tomcat/bin/startup.sh | grep -o "started."




