image: $CI_REGISTRY/root/myusine/docker:19

stages:
  - builds
  - tests
  - deploys

before_script:
  - >
    echo "$CI_REGISTRY_PASSWORD" | 
    docker login $CI_REGISTRY 
    -u $CI_REGISTRY_USER 
    --password-stdin

# appeler le pipeline d'un autre projet
call_stack:
  # stage de début par défaut
  stage: .pre
  trigger:
    project: root/stack
    branch: master
    # faire dépendre la suite du pipeline principal
    # du résultat du pipeline importé
    strategy: depend

build:
  stage: builds
  script:
    - docker build -t $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 .
    - docker push $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0

test:
  stage: tests
  script:
    - >
      docker container run 
      $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 
      /opt/tomcat/bin/startup.sh | grep -o "started."

push:
  stage: deploys
  script:
    - >
      docker tag
      $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0
      $CI_REGISTRY/root/myusine/my_tomcat:1.0
    - docker push $CI_REGISTRY/root/myusine/my_tomcat:1.0

staging:
  stage: deploys
  image: $CI_REGISTRY/root/myusine/ansible:ready
  before_script:
    - |
      echo "$STAGING_PKEY" > ansible_pkey
      chmod 700 .
      chmod 400 ansible
  script:
    - ansible-playbook -e "ansible_become_pass=$STAGING_PSSWD" playbook.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment:
    name: staging
    url: "http://192.168.1.77:8080"

    

