# image par défaut du pipeline
image: docker:19.03

stages:
  - builds

build:
  stage: builds
  script:
    - >
      echo "$CI_REGISTRY_PASSWORD" | 
      docker login $CI_REGISTRY 
      -u $CI_REGISTRY_USER 
      --password-stdin
    - docker build -t $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 .
    - docker push $CI_REGISTRY/root/myusine/my_tomcat_tmp:1.0 .

    

