# image par défaut du pipeline
image: gitlab.myusine.fr:5050/root/myusine/ubuntu:focal

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - builds
  - tests
  - deploy

build:
  stage: builds
  script:
    - echo "Build 1"
    - mkdir artifacts
    # production d'un rapport de build
    - echo "content" > artifacts/report
  # prélèvement d'artefacts dans des chemins
  # avec durée de vie
  artifacts:
    expire_in: 1 hour
    paths:
      - artifacts/

test:
  stage: tests
  # disponibilité des artefacts amont 
  # dans les jobs aval
  script:
    - echo "Test 1"
    - cat artifacts/report

deploy:
  stage: deploys
  script:
    - echo "Deploy"


