# image par défaut du pipeline
image: ubuntu:focal

build:
  script:
    # valeur de clé sur plusieurs lignes telle quelle
    - |
      echo "Build"
      echo "End"

test:
  image: python:rc-slim-buster
  script:
    # répartition d'une ligne longue sur plusieurs ligne
    - >
      echo "Test" && 
      echo "d'une" && 
      echo "commande" && 
      echo "arbitraitrement" && 
      echo "longue"