# image par défaut du pipeline
image: gitlab.myusine.fr:5050/root/myusine/ubuntu:focal

stages:
  - triggers

trigger1:
  stage: triggers
  trigger:
    include: module_1/module1.yml

trigger2:
  stage: triggers
  trigger:
    include: module_2/module2.yml