image: $CI_REGISTRY_IMAGE/docker:19

stages:
  - builds
  - tests
  - deploys

before_script:
  - >
    echo "$CI_REGISTRY_PASSWORD" | 
    docker login $CI_REGISTRY 
    -u $CI_REGISTRY_USER 
    --password-stdin

# appeler le pipeline d'un autre projet
.call_stack:
  # stage de début par défaut
  stage: .pre
  trigger:
    project: root/stack
    branch: master
    # faire dépendre la suite du pipeline principal
    # du résultat du pipeline importé
    strategy: depend

.build:
  stage: builds
  script:
    - docker build -t $CI_REGISTRY_IMAGE/my_tomcat_tmp:1.0 .
    - docker push $CI_REGISTRY_IMAGE/my_tomcat_tmp:1.0
  rules:
    - changes: [Dockerfile]

.test:
  stage: tests
  script:
    - >
      docker container run 
      $CI_REGISTRY_IMAGE/my_tomcat_tmp:1.0 
      /opt/tomcat/bin/startup.sh | grep -o "started."
  rules:
    - changes: [Dockerfile]

scan:
  stage: tests
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  variables:
    # on n'utilise pas le code du dépôt
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE/my_tomcat_tmp:1.0
  script:
    - trivy --version
  rules:
    - changes: [Dockerfile]  

.push:
  stage: deploys
  script:
    - >
      docker tag
      $CI_REGISTRY_IMAGE/my_tomcat_tmp:1.0
      $CI_REGISTRY_IMAGE/my_tomcat:1.0
    - docker push $CI_REGISTRY_IMAGE/my_tomcat:1.0
  rules:
    - changes: [Dockerfile]

.staging:
  stage: deploys
  image: $CI_REGISTRY_IMAGE/ansible:ready
  before_script:
    - |
      echo "$STAGING_PKEY" > ansible_pkey
      chmod 700 .
      chmod 400 ansible_pkey
  script:
    - ansible-playbook -e "ansible_become_pass=$STAGING_PSSWD" playbook.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment:
    name: staging
    url: "http://192.168.1.77:8080"

    

