# image par défaut du pipeline
image: gitlab.myusine.fr:5050/root/myusine/ubuntu:focal

stages:
  - builds
  - tests

build:
  stage: builds
  script:
    - echo "Build"

test:
  stage: tests
  script:
    - echo "Test"