[[runners]]
  name = "gitlab"
  url = "https://gitlab.myusine.fr/"
  token = "z9fnuwYxiy2LqvLqomgV"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    extra_hosts = ["gitlab.myusine.fr:172.17.0.1"]
    shm_size = 0