test_stack:
  image: docker/compose:latest
  # services:
  #   - docker:dind 
  script:
    - docker-compose -f wordpress-compose.yml up -d
    - sleep 15
    - docker-compose -f wordpress-compose.yml ps | grep -o "(healthy)"